export const SYMBOL_TO_CHAIN: { [key: string]: string } = {
  ETH: 'ethereum',
  BNB: 'binancecoin',
  MATIC: 'matic-network',
  GLMR: 'moonbeam',
  AVAX: 'avalanche-2',
  CELO: 'celo',
  FTM: 'fantom',
  xDAI: 'xdai',
  MTR: 'meter',
  MOVR: 'moonriver',
  ONE: 'harmony',
  KAVA: 'kava',
  KLAY: 'klay-token',
  CORE: 'coredaoorg',
  FUSE: 'fuse-network-token',
  MNT: 'mantle',
  METIS: 'metis-token',
  SMR: 'shimmer',
}
