import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import { Header } from './_components/header'
import { Footer } from './_components/footer'
import { Web3Provider } from './_providers/web3'
import { Toaster } from '@/components/ui/toaster'

const lato = Lato({
  weight: ['100', '300', '400', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`bg-background bg-[url('/bbblur.svg')] bg-no-repeat bg-center bg-cover ${lato.className}`}
      >
        <Web3Provider>
          <div className="flex flex-col w-full items-center justify-center min-h-screen">
            <Header />
            <main className="container flex flex-col w-full items-center justify-center py-24">
              {children}
              <div className="grow" />
            </main>
            <div className="grow" />
            <Footer />
          </div>
        </Web3Provider>
        <Toaster />
      </body>
    </html>
  )
}
