import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen bg-zinc-950 w-full items-center justify-center ${inter.className}`}
      >
        <main className="flex flex-col min-h-screen w-full items-center justify-center">
          {children}
          <div className="grow" />
        </main>
      </body>
    </html>
  )
}
