import {
  arbitrum,
  arbitrumNova,
  avalanche,
  base,
  bsc,
  celo,
  coreDao,
  fantom,
  fuse,
  gnosis,
  harmonyOne,
  kava,
  klaytn,
  linea,
  mantle,
  meter,
  moonbeam,
  moonriver,
  opBNB,
  optimism,
  polygon,
  polygonZkEvm,
  scroll,
  zkSync,
  zora,
  metis,
  shimmer,
} from 'wagmi/chains'

const wagmiChains = [
  zkSync,
  polygon,
  arbitrumNova,
  bsc,
  linea,
  arbitrum,
  scroll,
  optimism,
  base,
  moonbeam,
  avalanche,
  fantom,
  celo,
  gnosis,
  polygonZkEvm,
  meter,
  moonriver,
  harmonyOne,
  opBNB,
  kava,
  zora,
  klaytn,
  coreDao,
  fuse,
  mantle,
  metis,
  shimmer,
]

const chainImages = {
  324: '/chain-logo/zk.svg',
  42170: '/chain-logo/arb-nova.svg',
  56: '/chain-logo/bnb.svg',
  137: '/chain-logo/polygon.svg',
  59144: '/chain-logo/linea.svg',
  42161: '/chain-logo/arb.svg',
  534352: '/chain-logo/scroll.svg',
  10: '/chain-logo/optimism.svg',
  8453: '/chain-logo/base.svg',
  1284: '/chain-logo/moonbeam.svg',
  43114: '/chain-logo/avalanche.svg',
  250: '/chain-logo/fantom.svg',
  42220: '/chain-logo/celo.svg',
  100: '/chain-logo/gnosis.svg',
  1101: '/chain-logo/polygon-zk.svg',
  82: '/chain-logo/meter.svg',
  1285: '/chain-logo/moonriver.svg',
  1666600000: '/chain-logo/harmony.svg',
  204: '/chain-logo/op-bnb.svg',
  2222: '/chain-logo/kava.svg',
  7777777: '/chain-logo/zora.svg',
  8217: '/chain-logo/klaytn.svg',
  1116: '/chain-logo/core-dao.svg',
  5000: '/chain-logo/mantle.svg',
  122: '/chain-logo/fuse.svg',
  1088: '/chain-logo/metis.svg',
  148: '/chain-logo/shimmer-evm.svg',
}

export const chains = wagmiChains.map((chain) => {
  return { ...chain, iconUrl: chainImages[chain.id] }
}) as any
